CRITICAL - 2021-01-11 21:00:07 --> Undefined property: App\Controllers\Auth::$loginModel
#0 C:\xampp\htdocs\ci4app\app\Controllers\Auth.php(49): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 49, Array)
#1 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(931): App\Controllers\Auth->loging()
#2 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4app\public\index.php(44): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\ci4app\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2021-01-11 21:26:35 --> Undefined variable: validation
#0 C:\xampp\htdocs\ci4app\app\Views\auth\registration.php(12): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 12, Array)
#1 C:\xampp\htdocs\ci4app\system\View\View.php(219): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4app\system\Common.php(1213): CodeIgniter\View\View->render('auth/registrati...', Array, true)
#3 C:\xampp\htdocs\ci4app\app\Controllers\Auth.php(88): view('auth/registrati...')
#4 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(931): App\Controllers\Auth->registration()
#5 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#6 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci4app\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\ci4app\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2021-01-11 21:44:32 --> Undefined property: App\Controllers\Auth::$loginModel
#0 C:\xampp\htdocs\ci4app\app\Controllers\Auth.php(72): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 72, Array)
#1 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(931): App\Controllers\Auth->loging()
#2 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4app\public\index.php(44): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\ci4app\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2021-01-11 22:13:46 --> Allowed fields must be specified for model: App\Models\AuthModel
#0 C:\xampp\htdocs\ci4app\system\BaseModel.php(1240): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Auth...')
#1 C:\xampp\htdocs\ci4app\system\BaseModel.php(755): CodeIgniter\BaseModel->doProtectFields(Array)
#2 C:\xampp\htdocs\ci4app\system\Model.php(672): CodeIgniter\BaseModel->insert(Array, false, NULL)
#3 C:\xampp\htdocs\ci4app\system\BaseModel.php(668): CodeIgniter\Model->insert(Array, false)
#4 C:\xampp\htdocs\ci4app\app\Controllers\Auth.php(130): CodeIgniter\BaseModel->save(Array)
#5 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(931): App\Controllers\Auth->register()
#6 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4app\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\ci4app\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2021-01-11 22:15:57 --> Allowed fields must be specified for model: App\Models\AuthModel
#0 C:\xampp\htdocs\ci4app\system\BaseModel.php(1240): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Auth...')
#1 C:\xampp\htdocs\ci4app\system\BaseModel.php(755): CodeIgniter\BaseModel->doProtectFields(Array)
#2 C:\xampp\htdocs\ci4app\system\Model.php(672): CodeIgniter\BaseModel->insert(Array, false, NULL)
#3 C:\xampp\htdocs\ci4app\system\BaseModel.php(668): CodeIgniter\Model->insert(Array, false)
#4 C:\xampp\htdocs\ci4app\app\Controllers\Auth.php(130): CodeIgniter\BaseModel->save(Array)
#5 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(931): App\Controllers\Auth->register()
#6 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4app\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\ci4app\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2021-01-11 22:17:29 --> Allowed fields must be specified for model: App\Models\AuthModel
#0 C:\xampp\htdocs\ci4app\system\BaseModel.php(1240): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Auth...')
#1 C:\xampp\htdocs\ci4app\system\BaseModel.php(755): CodeIgniter\BaseModel->doProtectFields(Array)
#2 C:\xampp\htdocs\ci4app\system\Model.php(672): CodeIgniter\BaseModel->insert(Array, false, NULL)
#3 C:\xampp\htdocs\ci4app\system\BaseModel.php(668): CodeIgniter\Model->insert(Array, false)
#4 C:\xampp\htdocs\ci4app\app\Controllers\Auth.php(130): CodeIgniter\BaseModel->save(Array)
#5 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(931): App\Controllers\Auth->register()
#6 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4app\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\ci4app\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#10 {main}
ERROR - 2021-01-11 22:18:59 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\ci4app\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\ci4app\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `us...')
#1 C:\xampp\htdocs\ci4app\system\Database\BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\ci4app\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\ci4app\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\ci4app\system\Model.php(263): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\ci4app\system\BaseModel.php(777): CodeIgniter\Model->doInsert(Array, NULL)
#6 C:\xampp\htdocs\ci4app\system\Model.php(672): CodeIgniter\BaseModel->insert(Array, false, NULL)
#7 C:\xampp\htdocs\ci4app\system\BaseModel.php(668): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\ci4app\app\Controllers\Auth.php(130): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(931): App\Controllers\Auth->register()
#10 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ci4app\public\index.php(44): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\ci4app\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2021-01-11 22:18:59 --> Unknown column 'created_at' in 'field list'
#0 C:\xampp\htdocs\ci4app\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `us...')
#1 C:\xampp\htdocs\ci4app\system\Database\BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\ci4app\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\ci4app\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\ci4app\system\Model.php(263): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\ci4app\system\BaseModel.php(777): CodeIgniter\Model->doInsert(Array, NULL)
#6 C:\xampp\htdocs\ci4app\system\Model.php(672): CodeIgniter\BaseModel->insert(Array, false, NULL)
#7 C:\xampp\htdocs\ci4app\system\BaseModel.php(668): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\ci4app\app\Controllers\Auth.php(130): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(931): App\Controllers\Auth->register()
#10 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ci4app\public\index.php(44): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\ci4app\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#14 {main}
ERROR - 2021-01-11 22:20:12 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\ci4app\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\ci4app\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `us...')
#1 C:\xampp\htdocs\ci4app\system\Database\BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\ci4app\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\ci4app\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\ci4app\system\Model.php(263): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\ci4app\system\BaseModel.php(777): CodeIgniter\Model->doInsert(Array, NULL)
#6 C:\xampp\htdocs\ci4app\system\Model.php(672): CodeIgniter\BaseModel->insert(Array, false, NULL)
#7 C:\xampp\htdocs\ci4app\system\BaseModel.php(668): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\ci4app\app\Controllers\Auth.php(130): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(931): App\Controllers\Auth->register()
#10 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ci4app\public\index.php(44): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\ci4app\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2021-01-11 22:20:12 --> Unknown column 'updated_at' in 'field list'
#0 C:\xampp\htdocs\ci4app\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `us...')
#1 C:\xampp\htdocs\ci4app\system\Database\BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\ci4app\system\Database\BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\ci4app\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\ci4app\system\Model.php(263): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\ci4app\system\BaseModel.php(777): CodeIgniter\Model->doInsert(Array, NULL)
#6 C:\xampp\htdocs\ci4app\system\Model.php(672): CodeIgniter\BaseModel->insert(Array, false, NULL)
#7 C:\xampp\htdocs\ci4app\system\BaseModel.php(668): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\ci4app\app\Controllers\Auth.php(130): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(931): App\Controllers\Auth->register()
#10 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\ci4app\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ci4app\public\index.php(44): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\ci4app\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#14 {main}
